# Generated by Django 4.0.4 on 2022-05-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='autor',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tema',
            name='añoLanzamiento',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='musico',
            name='email',
            field=models.EmailField(max_length=40),
        ),
    ]
