# Generated by Django 4.0.4 on 2022-05-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicApp', '0002_tema_autor_tema_añolanzamiento_alter_musico_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tema',
            name='autor',
            field=models.CharField(max_length=50),
        ),
    ]
